import { expect, test } from "./fixtures";

test("A parent sends the weekly award and the child opens it, returns home and keeps their character choices", async ({ page, isMobile }) => {
  await page.goto("/#/we-live-happily-here");
  const launch = page.locator("#app-prototype").getByRole("button", { name: "Try the App", exact: true });
  await launch.click();
  const app = page.getByRole("dialog", { name: "App Prototype" });
  const parent = app.locator('[data-device="parent"]');
  const child = app.locator('[data-device="child"]');
  const showParent = async () => { if (isMobile) await app.getByRole("button", { name: "הצגת המסך של אמא" }).click(); };
  const showChild = async () => { if (isMobile) await app.getByRole("button", { name: "הצגת המסך של הילד" }).click(); };
  await showChild();
  await child.getByRole("button", { name: "הצטרפות לאפליקציה" }).click();
  await child.getByRole("button", { name: "ירוק", exact: true }).click();
  await child.getByRole("button", { name: "אביזרים", exact: true }).click();
  await child.getByRole("button", { name: "משקפיים", exact: true }).click();
  await child.getByRole("button", { name: "שמירת הדמות" }).click();
  await showParent();
  await parent.getByRole("button", { name: "סטטוס", exact: true }).click();
  await parent.getByRole("button", { name: /קלפי השבוע/ }).click();
  await expect(child.locator('[data-screen="home"]')).toHaveCount(1);
  await expect(child.locator('img[src$="award-notification.png"]')).toHaveCount(0);
  const send = parent.getByRole("button", { name: "שלח לשחקנים", exact: true });
  await expect(send).toHaveAttribute("aria-pressed", "false");
  if (isMobile) await send.tap(); else { await send.focus(); await page.keyboard.press("Enter"); }
  await expect(child.getByRole("heading", { name: "קיבלת את קלף השבוע!", exact: true })).toBeFocused();
  await expect(child.locator('img[src$="award-notification.png"]')).toBeVisible();
  const open = child.getByRole("button", { name: "פתיחת קלף השבוע", exact: true });
  if (isMobile) await open.tap(); else { await open.focus(); await page.keyboard.press("Enter"); }
  await expect(child.getByRole("heading", { name: "קלף השבוע!", exact: true })).toBeFocused();
  await expect(child.locator('img[src$="weekly-award.png"]')).toBeVisible();
  await expect(child.getByRole("region", { name: "תעודת הצטיינות" })).toContainText("דני ויובל");
  expect(await child.locator('[data-screen="award"]').evaluate(el => el.scrollHeight === el.clientHeight && el.scrollWidth === el.clientWidth)).toBe(true);
  const close = child.getByRole("button", { name: "סגירת קלף השבוע וחזרה הביתה", exact: true });
  if (isMobile) await close.tap(); else { await close.focus(); await page.keyboard.press("Enter"); }
  await expect(child.getByRole("heading", { name: "שלום דני!", exact: true })).toBeFocused();
  await expect(child.getByRole("button", { name: "שמירת הדמות" })).toHaveAttribute("aria-pressed", "true");
  await expect(child.locator("img[data-character]")).toHaveAttribute("data-color", "green");
  await expect(child.locator("img[data-accessory]")).toHaveAttribute("data-accessory", "glasses");
  await expect(child.getByText("0 משחקים היום", { exact: true })).toBeVisible();
  await child.getByRole("button", { name: "משקפיים", exact: true }).click();
  await child.getByRole("button", { name: "צבע", exact: true }).click();
  await child.getByRole("button", { name: "כתום", exact: true }).click();
  await expect(child.getByRole("img", { name: "דוב עם תעודת הצטיינות", exact: true })).toHaveAttribute("src", /bear-awarded-source.png$/);
  await child.getByRole("button", { name: "בחזרה להודעת ההצטיינות", exact: true }).click();
  await open.click();
  await child.getByRole("button", { name: "למסך הבית של הילד", exact: true }).click();
  await expect(child.getByRole("img", { name: "דוב עם תעודת הצטיינות", exact: true })).toBeVisible();
  await showParent();
  await expect(send).toHaveAttribute("aria-pressed", "true");
  await expect(send).toBeDisabled();
  await parent.getByRole("button", { name: "בחזרה למשפחה", exact: true }).click();
  await parent.getByRole("button", { name: "סטטוס", exact: true }).click();
  await parent.getByRole("button", { name: /קלפי השבוע/ }).click();
  await expect(send).toBeDisabled();
  await expect(child.locator('[data-screen="home"]')).toHaveCount(1);
  await app.getByRole("button", { name: "Close app prototype" }).click();
  await expect(launch).toBeFocused();
  await launch.click();
  await showChild();
  await child.getByRole("button", { name: "הצטרפות לאפליקציה" }).click();
  await expect(child.locator('img[src$="bear-awarded-source.png"]')).toHaveCount(0);
  await expect(child.locator("img[data-character]")).toHaveAttribute("src", /bear-orange-source.png$/);
});

test("An award cancels a pending lobby launch while preserving the game invitation", async ({ page, isMobile }) => {
  await page.goto("/#/we-live-happily-here");
  await page.locator("#app-prototype").getByRole("button", { name: "Try the App", exact: true }).click();
  const app = page.getByRole("dialog", { name: "App Prototype" });
  const parent = app.locator('[data-device="parent"]');
  const child = app.locator('[data-device="child"]');
  for (const name of ["יובל", "דני", "משחק חדש", "מרחב אישי", "שלח הזמנה"]) await parent.getByRole("button", { name, exact: true }).click();
  await child.getByRole("button", { name: "יש לך הזמנה למשחק!", exact: true }).click();
  if (isMobile) await app.getByRole("button", { name: "הצגת המסך של אמא" }).click();
  await parent.getByRole("button", { name: "סטטוס", exact: true }).click();
  await parent.getByRole("button", { name: /קלפי השבוע/ }).click();
  await page.clock.install({ time: new Date("2026-09-24T09:00:00Z") });
  await page.clock.pauseAt(new Date("2026-09-24T09:01:00Z"));
  if (isMobile) await app.getByRole("button", { name: "הצגת המסך של הילד" }).click();
  await child.getByRole("button", { name: "אני מוכן!", exact: true }).click();
  if (isMobile) await app.getByRole("button", { name: "הצגת המסך של אמא" }).click();
  await parent.getByRole("button", { name: "שלח לשחקנים", exact: true }).click();
  await page.clock.runFor(1500);
  await expect(page.locator('iframe[src*="games/happily"]')).toHaveCount(0);
  await expect(child.locator('[data-screen="award-notification"]')).toBeVisible();
  await child.getByRole("button", { name: "פתיחת קלף השבוע", exact: true }).click();
  await child.getByRole("button", { name: "סגירת קלף השבוע וחזרה הביתה", exact: true }).click();
  await child.getByRole("button", { name: "בחזרה להזמנה", exact: true }).click();
  await child.getByRole("button", { name: "יש לך הזמנה למשחק!", exact: true }).click();
  await expect(child.locator('[aria-label="דני: עדיין לא מוכן"]')).toBeVisible();
  await expect(child.getByRole("button", { name: "אני מוכן!", exact: true })).toHaveAttribute("aria-pressed", "false");
});
